# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 636ae3583126347c7565a805013941b5b2034eb41393e5d4c24fc3151c99cd5f2d057112bfac0ebcfc38815995720bbb65809735d9ac9fb11e723d6343cc18c2
  AWS_ACCESS_KEY_ID: AKIAJUZ3RMGXG7MO42QQ
  AWS_SECRET_ACCESS_KEY: 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

test:
  secret_key_base: 977ede688b3d436c9e23ab9e491b7b254eee6be508e48d51f477c6c0a7f593204a7c9f5722c972f0ba427e1415fbd6a0b3cf5059c417e1fb54628861b0943108
  AWS_ACCESS_KEY_ID: AKIAJUZ3RMGXG7MO42QQ
  AWS_SECRET_ACCESS_KEY: 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

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  AWS_ACCESS_KEY_ID: AKIAJUZ3RMGXG7MO42QQ
  AWS_SECRET_ACCESS_KEY: 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

